version: '3.8'
services:
  database:
    build:
      context: ./database
    restart: always
  redis:
    image: redis:6-alpine
  auth:
    build:
      context: ./auth
      target: development
    volumes:
      - ./auth:/usr/src/app
    command: npm start
    env_file:
      - env/dev.env
  api:
    build:
      context: ./api
      target: development
    volumes:
      - ./api:/usr/src/app
    command: npm start
    env_file:
      - env/dev.env
  envoy:
    build:
      context: ./envoy
    ports:
      - 8080:8080
  # continuous test run for authservice
  auth-test:
    build:
      context: ./auth
      target: development
    volumes:
      - ./auth:/usr/src/app
    command: npm run test:watch
    # command: node --inspect-brk=0.0.0.0 -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand --watchAll
    env_file:
      - env/dev.env
  # continuous test run for the api
  api-test:
    build:
      context: ./api
      target: development
    volumes:
      - ./api:/usr/src/app
    command: npm run test:watch
    env_file:
      - env/dev.env
  # firebase emulators
  firebase-dev:
    build:
      context: ./firebase
      target: emulators
    command: firebase --project framesystem-v2 emulators:start
    env_file:
      - env/dev.env
    ports:
      - 4000:4000
      - 9099:9099
  frontend-dev:
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ng serve
    env_file:
      - env/dev.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 4200:4200
